### ISSUE TITLE
[Feature Request] Where can I find the documentation

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#1]
### What is your enhancement?
You say: What is in PRO Version?
Elements · 200
Plugins · 4
Example Pages · 8
+ Documentation
+ SASS Files
Where should I look for that documentation. Thank you

**Comment by devlinpadayachee** [comment]
Please attend to this

**Comment by johnleider** [comment]
I believe that the documentation is referring to the Vuetify documentation, https://vuetifyjs.com .

There currently is not any specific documentation on the custom components but we should be able to put something together.

**Comment by ghost** [comment]
That's right. Since it is made with 'vuetify', it refers to 'vuetify'.

https://www.creative-tim.com/product/vuetify-material-dashboard-pro?ref=vuetifyjs.com&partner=116160

**Comment by pacific202** [comment]
I think this issue could be closed if on the download page the documentation link pointed to the github home page instead of the vuetify docs:

https://github.com/creativetimofficial/ct-vuetify-material-dashboard-pro

**Comment by cborgia** [comment]
would be nice if this theme had docs similar to the [react](https://demos.creative-tim.com/material-dashboard-pro-react/#/documentation/tutorial) and [angular](https://demos.creative-tim.com/material-dashboard-angular2/#/documentation/tutorial) versions
