### ISSUE TITLE
[Bug] v-text-field with prefix not working as expected

### ISSUE THREAD

**Issue by Jojoooo1** [creativetimofficial/ct-vuetify-material-dashboard-pro#10]
### Version
1.0.3
### Reproduction link
https://demos.creative-tim.com/
### Operating System
Ubuntu 18.04
### Device
Dell XPS 15
### Browser & Version
Mozilla
### Steps to reproduce
Create v-text-field components with a prefix property
### What is expected?
Prefix should be on the left compare to the label
### What is actually happening?
Prefix is actually on top of the label hidding it

---
### Solution
none

**Comment by Jojoooo1** [comment]
![Capture du 2019-09-25 15-27-38](https://user-images.githubusercontent.com/17641873/65629023-094cb580-dfa9-11e9-897e-7a365c0a8a4a.png)

**Comment by johnleider** [comment]
Can you please provide an example markup that you are using?

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
