### ISSUE TITLE
[Feature Request] Hide footer and AppBar in Full Screen map

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#12]
### What is your enhancement?
In order to make **Full Screen** Map I would suggest to add/edit following:

Index.vue (src>views>dashboard)

><**dashboard-core-app-bar v-model="expandOnHover" v-if="this.$route.name !== 'Full Screen Map'"/>**

View.vue (src>views>dashboard>components>core)
> <**dashboard-core-footer v-if="this.$route.name !== 'Full Screen Map'"/**>

**Comment by johnleider** [comment]
Thank you for your suggestion! Unfortunately this is not a feature we are currently considering.
