### ISSUE TITLE
[Bug] Tab titles are not visible in Wizard

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#13]
### Version
1.0.3
### Reproduction link
http://vmd.udaconsulting.com/#/forms/wizard
### Operating System
Windows 10
### Device
PC
### Browser & Version
Firefox 70, Chrome 76
### Steps to reproduce
click Wizard from Drawer
### What is expected?
All tab titles should be readable
### What is actually happening?
Active tab's title is not visible

---
### Additional comments

![VMD-Wizard-bug](https://user-images.githubusercontent.com/54809428/66464344-78d1a300-ea87-11e9-910a-fadb88f85a61.png)

**Comment by camassucato** [comment]
Same problem here. After a clean npm install of the original vuetify-material-dashboard-pro package, the form wizard do not display the titles of the active tab on form wizard...

**Comment by marcpaskell** [comment]
there is a z-index on the v-tabs-slider-wrapper... 

https://github.com/vuetifyjs/vuetify/commit/f74b70a3c8534481b22d736c2d955a292892719a#diff-c01920eb94e738f56fae76ff0ddb8523

**Comment by johnleider** [comment]
resolved for next release.
