### ISSUE TITLE
[Bug] Custom fixed shadows do not look good if theme colours changed (vuetify)

### ISSUE THREAD

**Issue by razvanioan** [creativetimofficial/ct-vuetify-material-dashboard-pro#17]
### Version
2.0.0
### Reproduction link
http://theres-no-need-for-link-here.com
### Operating System
MacOSX 10.14.6
### Device
Mac
### Browser & Version
Any
### Steps to reproduce
1. Change theme colours in Vuetify
2. Check shadows (buttons, card headers, etc)
### What is expected?
To have a general shadow or dynamically built based on theme colours
### What is actually happening?
shadow colours matching default theme

---
### Solution

1. (A) Best would be to find the proper way to read theme variables defined in Vuetify config inside sass (I didn't find the proper way yet)
1. (B) Or at least define & use in overrides (in order to easily reconfigure them there as well if wanted, to match with the config) - what I did for the moment
2. use scss theme variables inside shadow configuration something like this (sass `rgba()` function can take a hex color parameter as well just fine, no need to convert into RGB)
```sass
box-shadow: 0 1px 2px 4px rgba($primary-color, .5)
```

**Comment by phillipa-llama** [comment]
Thank you for logging this! I was just about to log the same issue that I have been struggling with trying to work out where the weird red shadow could be configured to another shade! It looks terrible with my primary colour.

**Comment by johnleider** [comment]
This has been resolved. Will go out with the next release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
