### ISSUE TITLE
[Bug] Layout partially broken on dark mode

### ISSUE THREAD

**Issue by langaads** [creativetimofficial/ct-vuetify-material-dashboard-pro#18]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
windows 10
### Device
notebook 15" 4k resolution
### Browser & Version
chrome 77
### Steps to reproduce
open demo turn on dark mode while looking at the toolbar
### What is expected?
dark mode should only affect colors, not layout.
### What is actually happening?
some components are misplaced on dark mode

---
### Solution
review css for missing properties on dark mode
### Additional comments
reproduced on an android phone with chrome as well

![image](https://user-images.githubusercontent.com/13821505/67439573-fc81a880-f5cc-11e9-9c0d-be06bb555458.png)

**Comment by johnleider** [comment]
This has been resolved. Will go out with the next release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
