### ISSUE TITLE
[Bug] LInk to issues pages is wrong

### ISSUE THREAD

**Issue by davidolrik** [creativetimofficial/ct-vuetify-material-dashboard-pro#19]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/new-issue/vuetify-material-dashboard
### Operating System
Any
### Device
Any
### Browser & Version
Any
### Steps to reproduce
- Click on link https://www.creative-tim.com/new-issue/vuetify-material-dashboard

### What is expected?
Go to issues page
### What is actually happening?
404

---
### Solution
Fix link to point to https://www.creative-tim.com/new-issue/vuetify-material-dashboard-pro
(It's missing `-pro` at the end.)

**Comment by dragosct** [comment]
Hi, @davidolrik! Thank you for using our products. Please, can you tell us exactly where did you find the link? 

Regards, 
Dragos

**Comment by davidolrik** [comment]
In the zip file I downloaded after purchase.

**Comment by johnleider** [comment]
As far as I can see, this is working as expected now:

![image](https://user-images.githubusercontent.com/9064066/73315053-ac7e3780-41f4-11ea-934b-ac89065b0a2d.png)
