### ISSUE TITLE
[Bug] Scrolling in pages, such as login, lock, register

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#2]
### Version
Version 1.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/pages/login
### Operating System
Windows 10
### Device
PC Screen resolution: 1920X1080
### Browser & Version
Firefox, Chrome
### Steps to reproduce
Just navigate to login pages
### What is expected?
All links and elements are in the page.
### What is actually happening?
the page is not fitting the screen in terms of height, I should scroll down to see the footer

---

**Comment by devlinpadayachee** [comment]
Experiencing the same

**Comment by UDADeveloper** [comment]
This issue is fixed in v 1.0.1

**Comment by OdiljonQurbon** [comment]
closing issue
