### ISSUE TITLE
[Bug] Login page not responsive

### ISSUE THREAD

**Issue by phillipa-llama** [creativetimofficial/ct-vuetify-material-dashboard-pro#20]
### Version
2.0.0

### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/pages/login

### Operating System
Windows 10

### Device
PC

### Browser & Version
Latest Chrome & Firefox

Could not load this demo on Internet Explorer:
![image](https://user-images.githubusercontent.com/57439980/69607676-6ce97280-102e-11ea-89d3-17c99b6e3e2b.png)

### Steps to reproduce
1. Go to https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/pages/login
2. View in various device modes

### What is expected?
That the login page would be responsive (as the dashboard pages are) and usable on Tablet Portrait as well as Mobile  Portrait & Landscape, not only on Desktop and Tablet Landscape as it is currently.

### What is actually happening?

**On Desktop:**
![image](https://user-images.githubusercontent.com/57439980/68291924-87fe3d80-0093-11ea-9d88-3f79821a3337.png)

**On Tablet Portrait view (iPad):**
![image](https://user-images.githubusercontent.com/57439980/68291969-9e0bfe00-0093-11ea-8286-4598a71c14d3.png)
1. Where has the navigation gone? Users are unable to access the top links available on Desktop mode anywhere on this view.

**On Tablet Landscape view:** Displays perfectly.

**On Mobile Portrait view (iPhone 6):**
![image](https://user-images.githubusercontent.com/57439980/68292057-c562cb00-0093-11ea-8afc-6ed2dc6d046e.png)
1. Card elements too large for device width.
2. Footer Links are half covered.
3. Navigation gone as per Tablet Portrait view.

**On Mobile Landscape view:**
![image](https://user-images.githubusercontent.com/57439980/68292165-f4793c80-0093-11ea-98c5-b735fa8ac96c.png)
1. Footer Links hidden
2. Navigation also gone as per Mobile Portrait view.

**Comment by johnleider** [comment]
This has been resolved. It will be available in the next release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by phillipa-llama** [comment]
Thanks @johnleider 
Could you give us an idea of when the next release that will have all these fixes will actually be made available?

**Comment by phillipa-llama** [comment]
I have tested this in v2.1.0 and confirmed that it has been resolved. Thank you.
