### ISSUE TITLE
[Bug] Transparent rectangle with shadow remains after closing Snackbar

### ISSUE THREAD

**Issue by phillipa-llama** [creativetimofficial/ct-vuetify-material-dashboard-pro#21]
### Version
2.0.0

### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications

### Operating System
Windows 10

### Device
PC

### Browser & Version
Latest Chrome & Firefox

Could not load this demo on Internet Explorer:
![image](https://user-images.githubusercontent.com/57439980/69607191-63133f80-102d-11ea-88bf-3f04731fdfbb.png)

### Steps to reproduce
1. Go to https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications
2. Click on snackbar Locations > TOP CENTER
3. Click on the snackbar close icon

### What is expected?
When the snackbar is closed manually, nothing should remain displaying over the page content

**What is actually happening?**
Transparent rectangle remains behind.

![image](https://user-images.githubusercontent.com/57439980/68575991-e18cb080-0475-11ea-9205-af535bbe48aa.png)

You can recreate this with all the 6 Snackbar Locations. I picked it up because I was testing with shorter copy, which also displays this transparent rectangle:

![image](https://user-images.githubusercontent.com/57439980/68576087-1b5db700-0476-11ea-9be7-6a1d4b524283.png)

**Comment by edwardsph** [comment]
I have having the same issues - this component cannot be used in its current state, particularly with shorter text as in the second screenshot.

**Comment by johnleider** [comment]
The shadow issue has been resolved. In regards to the IE11, seems to be coming from `vue-world-map`. Workaround until next release is to add _vue-world-map_ to your transpileDependencies in `vue.config.js`

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by phillipa-llama** [comment]
@johnleider I have downloaded and run the updated Vuetify Material Dashboard PRO Version 2.1.0 and also checked on your LIVE preview (is this running the latest version?).

And can still recreate this issue.

On your LIVE preview:
![image](https://user-images.githubusercontent.com/57439980/73528276-43c5d380-441d-11ea-82f4-4b1bbfc0f18d.png)

On my local instance of Version 2.1.0
![image](https://user-images.githubusercontent.com/57439980/73528375-78d22600-441d-11ea-886f-3cc3bb74ec25.png)


Steps to recreate:
Go to https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications
Click on Snackbar Locations > "Top Center"
Click on the close button of the notification that opens
See shadow box remains on screen.

**Comment by phillipa-llama** [comment]
As I cannot re-open this issue, I have re-logged it for v2.1.0 as Bug #32
