### ISSUE TITLE
How do I download theme for Vuetify 1.x?

### ISSUE THREAD

**Issue by nidheeshdas** [creativetimofficial/ct-vuetify-material-dashboard-pro#22]
### Version
2
### Reproduction link
https://v15.vuetifyjs.com
### Operating System
Macos
### Device
Macbook
### Browser & Version
Chrome 70
### Steps to reproduce
I'm using Vuetify 1.5. 
How do I download Theme for Vuetify 1.5? 
### What is expected?
Tim's theme for Vuetify 1.5
### What is actually happening?
Tim's theme for Vuetify 2

---
### Solution
Access to Github code repo so that we can download whichever version we want.
Or a download link for Theme that supports Vuetify 1.x

**Comment by johnleider** [comment]
You should submit a request on the contact-us page: https://www.creative-tim.com/contact-us
