### ISSUE TITLE
[Bug] Text styling issue in dark mode

### ISSUE THREAD

**Issue by edwardsph** [creativetimofficial/ct-vuetify-material-dashboard-pro#23]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Latest Chrome & Firefox
### Steps to reproduce
1. Switch to dark mode in settings menu
2. Click on account menu
### What is expected?
Readable menu items as in notifications menu
### What is actually happening?
Unreadable as they are grey (RGB 51,51,51) on grey (RGB 66,66,66)

---
### Solution
Issue is with fixed styling in AppBarItem:
class: {
  'black--text': !hover,
  'white--text secondary elevation-12': hover,
},
This needs to have an alternative in dark mode

**Comment by edwardsph** [comment]
I changed the title as I realise there is a general issue with text coloring. Try the dialogs in https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications - text is not visible. Dark mode does not seem to be properly implemented.

**Comment by johnleider** [comment]
This has been resolved and will go out with next release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
