### ISSUE TITLE
Issue - Template in webpack encore

### ISSUE THREAD

**Issue by daymerfillad** [creativetimofficial/ct-vuetify-material-dashboard-pro#24]
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 ERROR  Failed to compile with 2 errors                                                                                                                                                                   17:07:25

 error  in ./assets/js/views/dashboard/Calendar.vue?vue&type=style&index=0&lang=sass

      border-bottom: none
                      ^
      Expected "{".
    ╷
150 │     border-bottom: none
    │                        ^
    ╵
  stdin 150:24  root stylesheet
      in C:\www\BaratieAppServer\assets\js\views\dashboard\Calendar.vue (line 150, column 24)

 @ ./assets/js/views/dashboard/Calendar.vue?vue&type=style&index=0&lang=sass 1:0-469 1:485-488 1:490-956 1:490-956
 @ ./assets/js/views/dashboard/Calendar.vue
 @ ./assets/js/router.js
 @ ./assets/js/app.js

 error  in ./assets/js/views/dashboard/Charts.vue?vue&type=style&index=0&lang=sass

      stroke: #00cae3 !important
                   ^
      Expected "{".
    ╷
441 │     stroke: #00cae3 !important
    │                     ^
    ╵
  stdin 441:21  root stylesheet
      in C:\www\BaratieAppServer\assets\js\views\dashboard\Charts.vue (line 441, column 21)

 @ ./assets/js/views/dashboard/Charts.vue?vue&type=style&index=0&lang=sass 1:0-467 1:483-486 1:488-952 1:488-952
 @ ./assets/js/views/dashboard/Charts.vue
 @ ./assets/js/router.js
 @ ./assets/js/app.js

![Sin título](https://user-images.githubusercontent.com/42991624/69921099-450f6a00-1487-11ea-8c90-f2fe0dc6072b.png)

**Comment by Voltisky** [comment]
Got same issue

**Comment by johnleider** [comment]
Going to need additional information. What are the steps to reproduce this?

**Comment by johnleider** [comment]
This is being closed due to inactivity.
