### ISSUE TITLE
Vee-Validate version 3

### ISSUE THREAD

**Issue by jcarlos66** [creativetimofficial/ct-vuetify-material-dashboard-pro#25]
please update the vee-validate dependencie to version 3 in  Vuetify Material Dashboard PRO  vee-validate is not the current version 3, is the version 2
thanks

**Comment by johnleider** [comment]
This has been resolved and will be in the next release.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jcarlos66** [comment]
thanks
