### ISSUE TITLE
[Bug] Error executing npm run dev command.

### ISSUE THREAD

**Issue by rafasts** [creativetimofficial/ct-vuetify-material-dashboard-pro#27]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/product/vuetify-material-dashboard-pro?ref=vuetifyjs.com&partner=116160
### Operating System
Windows 7 ultimate
### Device
ultrabook samsung
### Browser & Version
Chrome Versão 79.0.3945.79 (Versão oficial) 64 bits
### Steps to reproduce
1 - Execute npm install.
2 - Executei npm run dev.

Observação: Projeto original sem alterações.
### What is expected?
Run the command "npm run dev" and view the project in the browser.
### What is actually happening?
I executed the command "npm install" as directed by the site and everything happened normally.

However, executing the command "npm run dev" is giving an error and I can not see the project in the browser.

Error log in additional comment field below

---
### Additional comments
C:\github\WebFer\FrontEnd\vuetify-material-dashboard-pro-v2.0.0>npm run dev

> vuetify-material-dashboard-pro@2.0.0 dev C:\github\WebFer\FrontEnd\vuetify-material-dashboard-pro-v2.0.0
> vue-cli-service serve --open

 INFO  Starting development server...
40% building 224/245 modules 21 active ...rd-pro-v2.0.0\src\components\base\MaterialAlert.vue?vue&type=script&lang=js&(node:5280) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 VElement listeners added. Use emitter.setMaxListeners() to increase limit
98% after emitting CopyPlugin

 DONE  Compiled successfully in 349698ms                                                                    10:29:49 AM

  App running at:
  - Local:   http://localhost:8080/
  - Network: unavailable

  Note that the development build is not optimized.
  To create a production build, run npm run build.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuetify-material-dashboard-pro@2.0.0 dev: `vue-cli-service serve --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuetify-material-dashboard-pro@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rafael\AppData\Roaming\npm-cache\_logs\2019-12-19T12_29_50_749Z-debug.log

**Comment by johnleider** [comment]
Could you provide me with the `@vue/cli-plugin-babel` version in your package.json? It should be **^4.1.2**.

Otherwise, before we get into debugging your env, can you try installing and running it with yarn?

**Comment by johnleider** [comment]
This issue has been resolved and will go out with the next release.
