### ISSUE TITLE
[Bug] Tag dropdown and multi-level dropdown do not function correctly on demo site.

### ISSUE THREAD

**Issue by eric-swann-q2** [creativetimofficial/ct-vuetify-material-dashboard-pro#28]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/forms/extended
### Operating System
Mac Mojave
### Device
Macbook Pro
### Browser & Version
Chrome Version 79.0.3945.88 (Official Build) (64-bit)
### Steps to reproduce
Go to:
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/forms/extended

Try to remove a tag from the "Tag dropdown".  
Tag is not removed, error is shown in console.  
Try to click the dropdown, dropdown does not open. error is shown in console.

Repeat the steps above for the Multi-level dropdown on the same page.
### What is expected?
The tag dropdown and multi-level dropdown function
### What is actually happening?
Both controls err out when attempting to use them.

---

**Comment by johnleider** [comment]
Resolved. Will go out with the next release.
