### ISSUE TITLE
[Bug] Dashboard button is not functional when screen wide between 960-1260

### ISSUE THREAD

**Issue by UDADeveloper** [creativetimofficial/ct-vuetify-material-dashboard-pro#3]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Firefox 70, Chrome 76
### Steps to reproduce
1. Navigate to demo website
2. change your browser screen size to 960.
### What is expected?
Clicking dashboard button should open dashboard
### What is actually happening?
only dashboard button icon is changed, dashboard is not openned

---

**Comment by johnleider** [comment]
I've pushed a fix for this.

**Comment by OdiljonQurbon** [comment]
Thank you John, for this amazing template and your hard work for making it perfect. Do you have an idea where can I find latest version? I see only v 1.0.1 in my download section.
