### ISSUE TITLE
[Bug] Pages (Register/Login/Prices/Lock) do not work

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-vuetify-material-dashboard-pro#30]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/product/vuetify-material-dashboard-pro
### Operating System
Windows 10 2004
### Device
Lenovo P1
### Browser & Version
Chrome 79.0.3945.117
### Steps to reproduce
1. Download and extract Vuetify Material Dashboard PRO, change to src folder
2. Run 'yarn install'
3. Run 'yarn serve'
### What is expected?
All pages work as advertised
### What is actually happening?
The "Pages" (Login/Register/Pricing/Lock) do not show the respective form, just the background image. The form seems to be pushed out of view (margin-left: -100%) by the v-img element. 

---
### Solution
The form gets displayed if I remove the v-img element, but I'd like to keep the image. The vuetify documentation was not helpful.

**Comment by lionhp** [comment]
> ### Version
> 2.0.0
> 
> ### Reproduction link
> https://www.creative-tim.com/product/vuetify-material-dashboard-pro
> 
> ### Operating System
> Windows 10 2004
> 
> ### Device
> Lenovo P1
> 
> ### Browser & Version
> Chrome 79.0.3945.117
> 
> ### Steps to reproduce
> 1. Download and extract Vuetify Material Dashboard PRO, change to src folder
> 2. Run 'yarn install'
> 3. Run 'yarn serve'
> 
> ### What is expected?
> All pages work as advertised
> 
> ### What is actually happening?
> The "Pages" (Login/Register/Pricing/Lock) do not show the respective form, just the background image. The form seems to be pushed out of view (margin-left: -100%) by the v-img element.
> 
> ### Solution
> The form gets displayed if I remove the v-img element, but I'd like to keep the image. The vuetify documentation was not helpful.
> 
> ### Additional comments

I  had the same bug. I add `.v-responsive__content
      margin-left: auto !important` to View.vue solve this bug.It's seems working now.

**Comment by johnleider** [comment]
This has been resolved and will be available in the next release. Thank you for your patience.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
