### ISSUE TITLE
[Bug] Template is broken and full of errors

### ISSUE THREAD

**Issue by Jam3si** [creativetimofficial/ct-vuetify-material-dashboard-pro#31]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Win 10
### Device
HP Spectre
### Browser & Version
All browsers
### Steps to reproduce

    Download and extract Vuetify Material Dashboard PRO
    Run 'npm install'
    Run 'npm run serve'

### What is expected?
To work

### What is actually happening?
**Dashboard:**
- after downloading the template and installing it, I run npm serve, and  this is the result:
https://imgur.com/a/wCmgM9C - it hapens in all browsers

**Settings:**
It does not have colors https://imgur.com/89aircZ

**Login/Register/Price pages are not working at all:**
https://imgur.com/i3LGRYe
https://imgur.com/bbW9732

**Sidebar font not changed to black on white background:**
https://imgur.com/JE3NNH8

**Errors from console:**

**First:**
[Vuetify] [REMOVED] 'full-width' has been removed. You can safely omit it.

found in

```
---> <VMenu>
       <VCard>
         <MaterialCard> at src/components/base/MaterialCard.vue
           <DashboardFormsExtendedForms> at src/views/dashboard/forms/ExtendedForms.vue
             <VContent>
               <DashboardCoreView> at src/views/dashboard/components/core/View.vue
                 <VApp>
                   <DashboardIndex> at src/views/dashboard/Index.vue
                     <App> at src/App.vue
                       <Root>
```

**Second:**
[Vue warn]: The .native modifier for v-on is only valid on components but it was used on <div>.

found in

```
---> <VCalendarMonthly>
       <VCalendar>
         <VSheet>
           <VCard>
             <DashboardCalendar> at src/views/dashboard/Calendar.vue
               <VContent>
                 <DashboardCoreView> at src/views/dashboard/components/core/View.vue
                   <VApp>
                     <DashboardIndex> at src/views/dashboard/Index.vue
                       <App> at src/App.vue
                         <Root>
```

**Third:**
Object Components is depracted. It will be removed soon. localhost:8080

**Install issues:**
34 packages are looking for funding
  run `npm fund` for details

```
found 65 vulnerabilities (64 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
vuetify-material-dashboard-pro@2.0.0
+-- vuetify@2.2.6
| +-- type: github
| `-- url: https://github.com/sponsors/johnleider
+-- @babel/core@7.8.3
| +-- type: opencollective
| `-- url: https://opencollective.com/babel
+-- webpack@4.41.5
| +-- type: opencollective
| `-- url: https://opencollective.com/webpack
+-- browserslist@4.8.5
| +-- type: tidelift
| `-- url: https://tidelift.com/funding/github/npm/browserslist
+-- has-symbols@1.0.1, resolve@1.15.0, is-date-object@1.0.2, is-symbol@1.0.3, es-to-primitive@1.2.1, is-callable@1.1.5, is-regex@1.0.5, object-inspect@1.7.0, string.prototype.trimleft@2.1.1, string.prototype.trimright@2.1.1, es-abstract@1.17.4, string.prototype.padsta
rt@3.1.0, object.getownpropertydescriptors@2.1.0, util.promisify@1.0.1, string.prototype.padend@3.1.0, object.values@1.1.1, object-is@1.0.2, regexp.prototype.flags@1.3.0, deep-equal@1.1.1, is-string@1.0.5, array-includes@3.1.1, array.prototype.flat@1.2.3
| `-- url: https://github.com/sponsors/ljharb
+-- glob@7.1.6
| `-- url: https://github.com/sponsors/isaacs
+-- p-limit@2.2.2
| `-- url: https://github.com/sponsors/sindresorhus
+-- autoprefixer@9.7.4
| +-- type: tidelift
| `-- url: https://tidelift.com/funding/github/npm/autoprefixer
+-- postcss@7.0.26
| +-- type: tidelift
| `-- url: https://tidelift.com/funding/github/npm/postcss
+-- ansi-styles@4.2.1
| `-- url: https://github.com/chalk/ansi-styles?sponsor=1
+-- loglevel@1.6.6
| +-- type: tidelift
| `-- url: https://tidelift.com/subscription/pkg/npm-loglevel?utm_medium=referral&utm_source=npm_fund
+-- eslint@6.8.0
| `-- url: https://opencollective.com/eslint
`-- picomatch@2.2.1
  `-- url: https://github.com/sponsors/jonschlinkert
```

---
### Solution

 You are selling something else than is advertised. The template is broken and full of errors. 
Stop selling something that is broken and different from what are you advertising. Solve so many github issues, there are issues that are 6 months old

**Comment by johnleider** [comment]
I'm looking into this right now. Thank you for your patience.

**Comment by johnleider** [comment]
Okay, everything with the exception of the Calendar and Object Components is deprecated message, both of which I will need some additional information about your environment:

- node version
- npm version
- yarn version

**Comment by johnleider** [comment]
In regards to `npm fund`, I'm not sure I understand the statement. I'm not sure if a project exists nowadays that doesn't have some sort of Open Source dependency.

**Comment by Jam3si** [comment]
NPM: 6.13.4
Node: 12.14.1

npm fund is just line in result text when I run npm install. I just copy whole text after install. The problem is in 65 vulnerabilities.
```
found 65 vulnerabilities (64 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Thats the 'depracted messeges', what about layout problems? I think it will be saas issue. It is happening in Safari, Mozilla, Chrome. Both Windows and MacOS.

**Comment by johnleider** [comment]
I'm pinning this issue for other users that encounter these issues. The fixes are currently pending release and deployment from CT. Thank you everyone for your patience.

**Comment by johnleider** [comment]
The npm issues have been resolved and will go out with the next release. Thanks again for your patience.

**Comment by Jam3si** [comment]
Issues were not solved.

Sidebar:
https://imgur.com/J7raw1Y
https://imgur.com/tNpyB8F

1. Selected page has to have an white font 
2. When you open some list, the parent will disappear because it has white font insead of black

Also, why it is not possible to open new issue? Is this the "premium" support which I payed for...? The style issues are not related to Vuetify creator.
