### ISSUE TITLE
[Bug] Transparent rectangle with shadow remains after closing Snackbar

### ISSUE THREAD

**Issue by phillipa-llama** [creativetimofficial/ct-vuetify-material-dashboard-pro#32]
### Version
2.1.0

### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications

### Operating System
Windows 10

### Device
PC

### Browser & Version
Latest Chrome & Firefox

### Steps to reproduce
1. Go to https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/components/notifications
2. Click on snackbar Locations > TOP CENTER
3. Click on the snackbar close icon

### What is expected?
When the snackbar is closed manually, nothing should remain displaying over the page content

**What is actually happening?**
Transparent rectangle remains behind.

You can recreate this with all the 6 Snackbar Locations. I picked it up because I was testing with shorter copy, which also displays this transparent rectangle:

This issue was originally logged as #21 in Version 2.0.0 and closed, expected to be fixed in Version 2.1.0 but I am unable to re-open that ticket and am still experiencing the issue on my local installation of v2.1.0 and the online demo (which I presume is running v2.1.0)

![image](https://user-images.githubusercontent.com/57439980/73529724-da938f80-441f-11ea-8cf3-921d69545c36.png)

**Comment by johnleider** [comment]
Resolved. Will go out with next release.
