### ISSUE TITLE
[Bug] Country Flag Icons not Available

### ISSUE THREAD

**Issue by BenFranklin-1776** [creativetimofficial/ct-vuetify-material-dashboard-pro#34]
### Version
2.1.0
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/#/
### Operating System
Windows
### Device
PC
### Browser & Version
Chrome
### Steps to reproduce
Demo dashboard world map/sales components shows country flags. Only these six (6) flags are in the files. We need all country flags. Is there a source for the particular flags in the files? Please advise so we can get all countries of these flags. Thank you.
### What is expected?
All flag icons present in the files
### What is actually happening?
Only 6 country flags icons present in the files.

---

**Comment by BenFranklin-1776** [comment]
Code on demo site shows source: background-image: url("**https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/**US.png"); background-position: center center;

**Comment by johnleider** [comment]
Copy and save the images:

https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/US.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/DE.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/AU.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/GB.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/RO.png
https://demos.creative-tim.com/vue-material-dashboard-pro/img/flags/BR.png
