### ISSUE TITLE
Settings icon missing from settings overlay tab

### ISSUE THREAD

**Issue by subn3t** [creativetimofficial/ct-vuetify-material-dashboard-pro#36]
@/src/views/dashboard/components/core/Settings.vue

Line 14 should be something like `mdi-cog` rather than `mdi-settings`

**Comment by Selada** [comment]
Thank you very much! This has been bothering me forever! It was `mdi-settings` in an old version of Material Design Icons.

**Comment by johnleider** [comment]
Resolved for next release.
