### ISSUE TITLE
No Icons, scroll bar in nav drawer

### ISSUE THREAD

**Issue by pilotkid** [creativetimofficial/ct-vuetify-material-dashboard-pro#37]
Hello, after importing the src directory from the download after purchasing this theme there are a few bugs. Is there any more documentation on how to properly load this theme?

1. There is a scroll bar in the drawer
2. None of the Material Design icons show up
![image](https://user-images.githubusercontent.com/6385285/79184525-9c2c3080-7dd1-11ea-83af-8ec0a5b6a46d.png)

**Comment by Jam3si** [comment]
They are not maintaining this theme. Basicly, it is scam. I had this problems in January and they did not fixed them until now. They just said that it is problem of vuetify creator... not theirs..

**Comment by dragosct** [comment]
Hi guys! Thank you for working with our products. First of all, I want to say to @Jam3si that we respect his opinion, but we are a company with `1,133,770` developers and with the traffic of `2.1m unique IP's visits/month` so we can't afford to be a scam like you said. The product may have some bugs and it's normal and these bugs will be fixed for sure. [John Leider](https://github.com/johnleider) it's the founder of Vuetfiy and also he is the creator of this product. so basically he is the one who offers support for this product and for this reason we are asking our clients to go in the discord channel: https://discordapp.com/invite/s93b7Fv for receiving the support they need. Many of our users who bought this product are also in that discord channel and they're happy with the support that is received there.

Thank you for your understanding!

Regards,
Dragos

**Comment by Jam3si** [comment]
1. You are selling different product than is on your product page - that is scam
2. you are selling something broken for 5 months and you are not willing to repair it - that is scam
3. you are selling something and you say that it's someone else responsibility to maintain it - that is scam
4. My issue is open for 4. months, I wrote many times on discord channel, John said that he will look at it. IT WAS 4 MONTHS AGO - that is scam

Result = you can not say that this is OK.

**Comment by pilotkid** [comment]
I took 5 emails before they even responded, I do have to say that it seems quite scammy to me. 

I was able to get a refund thankfully, however, their support is quite lacking I cannot imagine how frustrated "`1,133,770`" developers are with this company. I am glad I was able to get out while I was still ahead.  

With the company defending themselves instead of actually assisting with the issue clearly shows where their priorities lie. Take the money, and run. That in and of itself should show that this is not an upstanding company. That is like if you called Amazon, and instead of helping you they gave you a sales pitch on why they are the best e-commerce site in the world. It is simply astonishing, what that unlimited support buys you with them.

Clearly they have never seen their own discord. All that it is, is people asking questions and being ignored by the staff. I asked this exact same question on the discord channel 3 times and did not get a response over the course of a working week. It seems to be an endless loop of dodging problems from the company. 

I'm sure that when you ignore the voices of your customers it is easy to come to the conclusion that everyone is happy.

**Comment by pilotkid** [comment]
> Hi guys! Thank you for working with our products. First of all, I want to say to @Jam3si that we respect his opinion, but we are a company with `1,133,770` developers and with the traffic of `2.1m unique IP's visits/month` so we can't afford to be a scam like you said. The product may have some bugs and it's normal and these bugs will be fixed for sure. [John Leider](https://github.com/johnleider) it's the founder of Vuetfiy and also he is the creator of this product. so basically he is the one who offers support for this product and for this reason we are asking our clients to go in the discord channel: https://discordapp.com/invite/s93b7Fv for receiving the support they need. Many of our users who bought this product are also in that discord channel and they're happy with the support that is received there.
> 
> Thank you for your understanding!
> 
> Regards,
> Dragos

Thank you for defending the company instead of actually helping with the issue. This comment right here displays

**Comment by alexandru-paduraru** [comment]
@pilotkid @Jam3si i gave a detailed response here https://github.com/creativetimofficial/ct-vuetify-material-dashboard-pro/issues/40, sorry for all the issues you had. We can provide refunds and let you keep the license/product and future updates till the new version will be released.

Hope you understand us.

Best,
Alex

Managing Parter @Creative Tim
