### ISSUE TITLE
Upgrading from v1.0.3 to v2.1.0

### ISSUE THREAD

**Issue by ricardonolan** [creativetimofficial/ct-vuetify-material-dashboard-pro#38]
Hi, 

have v1.0.3 currently installed, and want to upgrade to v2.1.0

Is it safe to simply overwrite and run `npm update`, or are there any breaking changes?
Is there another way to upgrade directly via npm command?

**Comment by johnleider** [comment]
It mostly pertains to updated packages and improvements. The upgrade should be relatively simple. Let me know if you have any specific issues.

**Comment by johnleider** [comment]
Closing as resolved.
