### ISSUE TITLE
[Bug] Styles Files Loading Multiple Times

### ISSUE THREAD

**Issue by devlinpadayachee** [creativetimofficial/ct-vuetify-material-dashboard-pro#4]
### Version
1.0.1
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/
### Operating System
Windows 110
### Device
PC
### Browser & Version
Chrome 
### Steps to reproduce
1. Load Vuetify Material Design Pro
2. Inspect Dom
3. Check Head Tags
4. Notice the same Style Files Loaded Multiple Times
### What is expected?
The Files Shoulld notbe loaded multiple times. This is even slowing down the Chrome Developer Tools
### What is actually happening?
Style Files are loaded a number of times.

---
### Additional comments
Hi, I have found and issue where the css files are being loaded multiple times for no reason. Please can you fix this issue and please let us know waht you have fixed so i can implement it on version 1.0.1, My messages were ignored before. Please see attached screen shots https://imgur.com/gallery/9koC4bk

**Comment by devlinpadayachee** [comment]
Here is another example.

![image](https://user-images.githubusercontent.com/4748730/64424244-d64d8b00-d0a8-11e9-8cb6-f6ddb2fb4861.png)

If you can see on the right hand side how many times the same files are loaded.

**Comment by johnleider** [comment]
Resolved. Will go out with next release.

**Comment by devlinpadayachee** [comment]
> Resolved. Will go out with next release.

Thanks John for the timeous reply. Please also include instructions on how to implement the fix if Im already using version 1.0.1 as i have already coded into the version.

**Comment by johnleider** [comment]
Remove the `overrides.scss` import from `main.scss` and import it anywhere else.

**Comment by devlinpadayachee** [comment]
WAs Fixed in 1.0.3 but its doing it again in 2.0.0. All in all the support for this library is rather shoddy. Fixes are taking too long for breaking changes

**Comment by devlinpadayachee** [comment]
> Remove the `overrides.scss` import from `main.scss` and import it anywhere else.

version 2.0.0 removes main.scss

**Comment by marcpaskell** [comment]
Remove import overrides.scss from **variables.scss** (was main.scss) and import from main.js
