### ISSUE TITLE
Is this compatible with Vuetify 2.3.1?

### ISSUE THREAD

**Issue by edwardsph** [creativetimofficial/ct-vuetify-material-dashboard-pro#41]
Are there any known issues in this dashboard with upgrading Vuetify to v2.3+

**Comment by edwardsph** [comment]
Thought I'd try it out and it seems OK. There are some deprecated classes so I updated those as per https://github.com/vuetifyjs/vuetify/releases#user-content-upgrade-guide but I noticed that MaterialStatsCard.vue uses body-3 which is not even defined by Vuetify so should be replaced by something appropriate.

**Comment by pilotkid** [comment]
Aren't you glad you paid good hard-earned money for their premium support?
![image](https://user-images.githubusercontent.com/6385285/87750519-ebab3f80-c7b8-11ea-9f4d-9a03068c31f3.png)

**Comment by johnleider** [comment]
Hey @edwardsph,

The typography classes were upgraded in v2.3 to support breakpoint based changes. With this a few classes changed. This will be updated with the next release.

Thank you,
