### ISSUE TITLE
The display of the downloaded file is not the same as the demo

### ISSUE THREAD

**Issue by blueplanet** [creativetimofficial/ct-vuetify-material-dashboard-pro#42]
@timcreative 

The background color of the downloaded file is ineffective.
Can you confirm this?

|Demo|Download file|
|------|-------------|
|<img width="1552" alt="Screen Shot 2020-07-01 at 8 40 11" src="https://user-images.githubusercontent.com/219833/86187381-9f37f100-bb76-11ea-8404-7695c3699268.png">|<img width="1552" alt="Screen Shot 2020-07-01 at 8 40 45" src="https://user-images.githubusercontent.com/219833/86187421-b545b180-bb76-11ea-8d07-70238ab6393b.png">|

**Comment by blueplanet** [comment]
The problem with the background color is only in development mode.
It's okay to build in production mode.

**Comment by johnleider** [comment]
This will be resolved in the next update which should be within the week. Thank you for your patience.

**Comment by johnleider** [comment]
The latest version has been given to CT. The updated download should be in their system.
