### ISSUE TITLE
Upcoming VMD rebuild

### ISSUE THREAD

**Issue by johnleider** [creativetimofficial/ct-vuetify-material-dashboard-pro#43]
I wanted to give an update on what is going on with VMD and address some of the concerns in regards to updates or support.

The initial VMD Free was built on v1 of Vuetify while VMD PRO was built months later on v2. This caused a major disconnect in solving issues and propagating fixes between the 2 versions. VMD Free was upgraded to v2 later on but it took way longer than it should have and it was still a separate project. The separation ended up being a bigger problem than I anticipated.

Ultimately this caused more help requests than I could handle. While VMD is built on top of Vuetify, not every aspect is custom and would result in numerous help requests that had nothing to do with the theme. Vuetify is a massive library and it was being confused as being built specifically for VMD.

Due to this I ultimately closed the premium-theme-support channel in Q4 of last year. Flash forward with covid and I didn't have the bandwidth to bring it back.

At this moment I'm about 50% done converting VMD to our current standardized structure (what's used in newer Vuetify themes). This version will accommodate both the Free and the PRO version of the theme and with any lucky resolve majority, if not all, of the issues that users were having.

I appreciate your patience and in the meantime I've re-opened the theme channel. If you have questions please feel free to reach out to me https://discord.gg/w2qKXtD.

Thank you,

John Leider

**Comment by nonoodles** [comment]
#40

**Comment by devlinpadayachee** [comment]
I would like a refund please. I feel as though I have not had the support I require. I eventually gave up asking. It's as if my money was stolen. At one point this template just did not so what I paid for, also I have that once you build with this template and an upgrade comes its almost impossible to incorporate the changes into your own app.

**Comment by dragosct** [comment]
Hi, @devlinpadayachee! Please write to us on the contact us section and give us your order ID to be able to proceed with the refund. 

Regards,
Dragos

**Comment by pilotkid** [comment]
@dragosct10 @johnleider. 

I appreciate you both finally giving this some attention.

I acknowledge this is not my place but maybe it would be a good idea to suspend sales of this theme until the next version is released to prevent more disgruntled customers.

**Comment by johnleider** [comment]
**Update:** New structure and all pages complete. Working on the custom styles and then we can start testing.

**Comment by johnleider** [comment]
**Update:** Styling is still in development and taking a little longer than I had hoped, but still making progress. I've been working to clean-up the code significantly as well and am quite happy with the results.

A note, the end of this month is going to be slow due to kids going back to school, the new Vuetify docs are releasing soon (check it out! https://next.vuetifyjs.com) and September 1st we kick off full development on the next version of Vuetify.

I greatly appreciate everyone's patience, thank you.

**Comment by nonoodles** [comment]
@johnleider Any further updates 2 months on?

**Comment by johnleider** [comment]
Sorry for going mia a bit there. We had the release of the new documentation and I've had a few personal family emergencies.

I'm going to try to wrap it up this week, 🤞

**Comment by johnleider** [comment]
**Update:** Rewrite is complete and is waiting on feedback and review. Releases next week.

**Comment by johnleider** [comment]
Small delay due to covid, preview of new splash art: 
![screen1](https://user-images.githubusercontent.com/9064066/99870992-c9796200-2b9c-11eb-812e-d41ebc161f28.png)

**Comment by nonoodles** [comment]
@johnleider @dragosct10 Any news on the release?

**Comment by johnleider** [comment]
THe updated version is done. It's out to CT and updated in the Vuetify store.

**Comment by edwardsph** [comment]
@johnleider Looking on CT I can still only see v2.1.0 and when I spoke to CT they said "Related to the latest update from John we still waiting for the push from his side on the vuetify material dashboard pro repo because the update is done."

**Comment by OdiljonQurbon** [comment]
> Looking on CT I can still only see v2.1.0

Same issue. Looking forward to the the updated code as soon as possible.

**Comment by Selada** [comment]
I had the opportunity to reach @johnleider in discord even before the support channel reopening. I was expecting this proper VMD version during my license period, as that expectation was to be ready anytime soon. In the meanwhile my license expired in September without ever having the appropriate update to a reasonable version. I would like to have access to it, as it was that expectation that kept me waiting without requesting a refund.

**Comment by SzabZol** [comment]
Any news here? The latest version is still 2.1.0.

**Comment by Selada** [comment]
@johnleider, could you please give us the legitimate right version? you've done it in the past with a user here in gitlab

**Comment by miaohf** [comment]
@johnleider
It's beatiful.
I bought this template from Creative Tim. Now the code is update to Version 2.1.0, Jun 26, 2020.
I found that the version on [vuetifyjs.com](https://store.vuetifyjs.com/products/vuetify-material-dashboard-pro) is updated.
Could you update it on  Creative Tim, pleas.
Thank you.

**Comment by johnleider** [comment]
I no longer maintain this theme. All updates will be provided by CT. Sorry for the inconvenience.

**Comment by dragosct** [comment]
Hi, @miaohf! We are preparing the new update with the Material 2 design and then the product will be on the latest version of vuetify. 

Regards,
Dragos
