### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by vmalawade** [creativetimofficial/ct-vuetify-material-dashboard-pro#44]
Just down loaded fresh copy of material dashboard and ran npm I on Mac OS - Catelina, Node 14.5.0 
I get 

npm WARN deprecated @hapi/joi@15.1.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

Can someone fix this or instructions of how to update my package.json ?

**Comment by vmalawade** [comment]
I get a error as follows on console.

http://s3.amazonaws.com/jsfile/21656496f07761af42.js net::ERR_ACCESS_DENIED

How do I get rid of it?

**Comment by johnleider** [comment]
They are just warnings and can happen due to the dependencies of other packages. You can use <https://www.npmjs.com/package/npm-check-updates> for a nice interface when dealing with upgrades or wait until the next version of the dashboard comes out in the next week.
