### ISSUE TITLE
Missing .js 

### ISSUE THREAD

**Issue by vmalawade** [creativetimofficial/ct-vuetify-material-dashboard-pro#45]
I just downloaded latest material-dashboard-pro
When loading a page I get 404 for 

http://s3.amazonaws.com/jsfile/21656496f07761af42.js

Please advise of how to fix it.

**Comment by johnleider** [comment]
Have you made any changes to the code? We don't use s3 aws for anything.

**Comment by vmalawade** [comment]
No changes,
Just download
npm i 
npm run serve

**Comment by johnleider** [comment]
Not enough information for anything actionable.
