### ISSUE TITLE
Deprecated and Outdated code

### ISSUE THREAD

**Issue by hmawla** [creativetimofficial/ct-vuetify-material-dashboard-pro#46]
I was just wondering if there is any update coming soon, since the Version 2.1.0 has many outdated and deprecated code and dependencies.

Thanx, and well done for such great project.

**Comment by pilotkid** [comment]
#43

**Comment by OdiljonQurbon** [comment]
@timcreative  When are you going to upload the updated version?

**Comment by johnleider** [comment]
The latest version has been given to CT. The updated download should be in their system.
