### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#47]
@timcreative When are you going to upload the updated version?

**Comment by nonoodles** [comment]
Every month or so I come and check on here. Every month is the same thing. No update.

@johnleider @timcreative @dragosct10 @alexandru-paduraru

**Comment by pilotkid** [comment]
@OdiljonQurbon I would suggest getting a refund. 

Until the new version comes out you can get a refund according to @alexandru-paduraru in #40 

> If there is somebody else who want a refund we will proceed with that and you can keep the product and the license till we will release the version that @johnleider is writing now.

**Comment by nonoodles** [comment]
@pilotkid I actually asked for a refund, they said no!

**Comment by pilotkid** [comment]
@nonoodles Shocker more lies from CreativeTim! Do a chargeback, I would also write to the BBB/trustpilot. They did not deliver the product promised. The premium support that is supposedly offered is not very evident in this repo, where they say to go to get support.

**Comment by johnleider** [comment]
The latest version has been given to CT. The updated download should be in their system.
