### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by karthiktrml** [creativetimofficial/ct-vuetify-material-dashboard-pro#48]
Hi, you got a great product and it makes development much easier.

I would like to use DatePicker component mentioned on the docs [here](https://demos.creative-tim.com/vue-material-dashboard-pro/documentation/component-docs/date-pickers.html#simple-examples)

But unable to re-produce using the code present on the document above.

**Comment by johnleider** [comment]
This would be a Vuetify specific question. I suggest searching their Discussion board or Discord server, https://community.vuetifyjs.com.
