### ISSUE TITLE
[Bug] Sidebar background options are not visible in Firefox

### ISSUE THREAD

**Issue by OdiljonQurbon** [creativetimofficial/ct-vuetify-material-dashboard-pro#6]
### Version
1.0.2
### Reproduction link
https://demos.creative-tim.com/vuetify-material-dashboard-pro/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Firefox 68.0.2 (64-bit), Firefox Developer 70.0b3 (64-bit)
### Steps to reproduce
1. Navigate Demo page
2. Click Settings menu
### What is expected?
to see black and orange circles under sidebar background options
### What is actually happening?
sidebar options are not visible

---

**Comment by johnleider** [comment]
Could you provide some additional information please? Maybe some screenshots. I'm not quite sure what the issue is.

**Comment by OdiljonQurbon** [comment]
![VMD-PRO-sidebar-bug](https://user-images.githubusercontent.com/54809428/66188322-b56c5b80-e68f-11e9-8a12-ea37f3128917.png)

**Comment by johnleider** [comment]
This has been resolved and is reflected on the demo site.
